### ISSUE TITLE
Is the GML test Testing Topology (corrupted geometries)

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#10]
What is the test scope for GML for topology. For example if a polygon geometry is not correct?

**Comment by rjmartell** [comment]
The geometry-related tests were developed to verify conformance with the GML-AIXM profile. See the [test suite documentation](http://opengeospatial.github.io/ets-gml32/). The tests also apply to any application-defined geometries that can substitute for the standard GML elements listed below:

* gml:Point 
* gml:Curve having the following curve segments: gml:ArcByCenterPoint, gml:CircleByCenterPoint, gml:Arc, gml;Circle, gml:GeodesicString, gml:Geodesic, gml: LineStringSegment 
* gml:OrientableCurve 
* gml:CompositeCurve 
* gml:Polygon 
* gml:Surface having the following surface patches: gml:PolygonPatch, gml:Rectangle, gmlTriangle

**Comment by rjmartell** [comment]
The tests for surface geometries (i.e. elements that substitute for gml:AbstractSurface) are defined in the `org.opengis.cite.iso19136.data.spatial.SurfaceTests` class:

* surfaceHasValidCRS 
* validSurfaceBoundary 
* validSurfaceOrientation
