### ISSUE TITLE
pointHasValidPosition - Java Null Pointer exception

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#11]
testing a gml file with GML 3.2 suite rel. 1.20 we got a ‘Java Null Pointer exception’ (we also get the same error testing with release 18). The point coordinates seems OK (length of coordinate tuple = CRS dimension -the point is located within the valid area of the CRS - axis order is correct). 

![pointhasvalidposition_javanullpointer_2](https://cloud.githubusercontent.com/assets/3738898/7838886/61a9938c-045d-11e5-8d27-d0389c2009fd.png)

**Comment by bermud** [comment]
Link to file is here: https://gist.github.com/bermud/ff67d9a79b63c16979a9

**Comment by rjmartell** [comment]
Looks like there is an issue with identifying the CRS (srsName="http://www.opengis.net/def/crs/EPSG/0/3045"). I'll investigate.

**Comment by rjmartell** [comment]
There is a fix pending, but the point coordinates are invalid: they do fall within not within the CRS area of use (3928493 227880, 8325798 772120).

````xml
<gml:Point xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="grid_origin_tiff"
	srsName="http://www.opengis.net/def/crs/EPSG/0/3045">
	<gml:pos>550780.00 4452960.00</gml:pos>
</gml:Point>
```

__Note__: The axis order should be N,E (see [EPSG Geodetic Parameter Registry](http://epsg-registry.org/)). It looks like the axis order was switched here.

**Comment by rjmartell** [comment]
Fixed NPE.
