### ISSUE TITLE
validSurfaceOrientation test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#12]
INSPIRE GML documents fail this test because ISO19107 is violated in the orientation of the surface when creating geometries.

From 19136, 10.5.10:
"A Surface is a 2-dimensional primitive and is composed of one or more surface patches as specified in ISO 19107:2003, 6.3.17.1."
 
From 19107, 6.3.17.1:
 
"The orientation of a surface chooses an "up" direction through the choice of the upward normal, which, if the surface is not a cycle, is the side of the surface from which the exterior boundary appears counterclockwise."

**Comment by bermud** [comment]
(From Richard)
A solution might be to introduce an application-specific conformance to ignore or overwrite  the surface orientations. 

GML only defines one conformance class for GML documents (2.4); it essentially requires “full” conformance. Perhaps a lesser level could be introduced that omits some “advanced” constraints.

**Comment by rjmartell** [comment]
Yes, this is a general constraint that applies to all conforming GML 3.2 documents. Specific violations may be ignored in some circumstances (at the risk of hindering interop with consumers that expect valid instances). Another option is to request that the ATS for GML 3.2 be amended to introduce a lesser conformance class for documents.
