### ISSUE TITLE
envelopeHasValidCRS fails if srsName is URL

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#13]
Test method “envelopeHasCRSReference” Fails if CRS is encoded according to INSPIRE,  i.e.  “http://www.opengis.net/def/crs/EPSG/0/EPSGcode “ while it succeeds if CRS is given as ”urn:ogc:def:crd:EPSG::EPSGcode”

(Reported By Epislon-Italia)

**Comment by rjmartell** [comment]
The `http` URI form should be acceptable (per [OGC 09-048r3, cl. 4.4)](http://portal.opengeospatial.org/files/?artifact_id=37802). I'll attempt to verify and add a bug report if confirmed.

**Comment by rjmartell** [comment]
An assertion error is thrown if the CRS reference is an 'http' URI. For example:

```xml
<gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2"
	srsName="http://www.opengis.net/def/crs/EPSG/0/32610">
	<gml:lowerCorner>514432 5429689</gml:lowerCorner>
	<gml:upperCorner>529130 5451619</gml:upperCorner>
</gml:Envelope>
```

The underlying exception is org.opengis.referencing.NoSuchAuthorityCodeException:  `Illegal argument: ‘code’=http://www.opengis.net/def/crs/EPSG/0/32610`
