### ISSUE TITLE
pointHasValidPosition - axis order

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#14]
The  Test method ‘pointHasValidPosition’  fails for most INSPIRE GML files due to different order of coordinates (Lon Lat ) instead of (Lat Lon).

Lost of tools assume Lon Lat order by default
- QGIS
- Tools for transforming PostGis DB table or shape file format to INSPIRE compliant GML have default Lon Lat, because PostGIS default is Lon Lat and shape files if often Lon Lat order

(Reported by Epsilon)

**Comment by rjmartell** [comment]
The axis order must be in accord with the applicable CRS definition. Note that the WMS 1.3 spec (B.3) defines the CRS *WGS 84 longitude-latitude*; it can be referenced as indicated in OGC 09-048r3: 

* `http://www.opengis.net/def/crs/OGC/1.3/CRS84`
* `urn:ogc:def:crs:OGC:1.3:CRS84`
