### ISSUE TITLE
Support validation of temporal elements in instance documents

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#15]
Version 1.21 verifies that temporal  _schema components_  are defined in accord with the rules for application schemas. However, all temporal elements in an _instance document_ are ignored.

**Comment by rjmartell** [comment]
The schema is checked for valid temporal type definitions in accord with conformance class A.1.7: `GML application schemas defining time`. Clause A.3 (_Abstract test suite for GML documents_) does not explicitly mention temporal elements, but instances are always validated against the relevant application schemas (A.3.4, Valid XML).

ATC-A.3.5 is a "catch-all" test requirement that covers "all other constraints specified by this International Standard."

**Comment by rjmartell** [comment]
This will likely be addressed in [OGC Testbed 12](http://www.opengeospatial.org/standards/requests/139), which calls for testing of temporal predicates in the WFS v2 test suite.
