### ISSUE TITLE
validSurfaceBoundary test method returns 'Polygon not closed' issue on a closed polygon

### ISSUE THREAD

**Issue by sMorrone** [opengeospatial/ets-gml32#16]
I get the following test log 
"Message d1e181_1:   
Test method validSurfaceBoundary: 
Exterior boundary of surface with @gml:id='_7c18c4d9-5ecf-4a96-b3ce-a654c4c485f0' is not closed. expected [true] but found [false]" 
Here's the gml snippet for the polygon:
 "gml:Surface 
gml:id="_7c18c4d9-5ecf-4a96-b3ce-a654c4c485f0" srsName="http://www.opengis.net/def/crs/EPSG/0/3044">
                    <gml:patches>
                        <gml:PolygonPatch>
                            <gml:exterior>
                                <gml:LinearRing>
                                    <gml:posList>557434.4392654571 4889943.440965306
                                        557416.8447309382 4889939.736659265 557404.8063477885
                                        4889951.774776376 557402.0282516262 4889961.034948599
                                        557400.176184925 4889969.369111807 557400.1761754069
                                        4889977.330709443 557434.8691827263 4889943.526953525
                                        557434.4392654571 4889943.440965306</gml:posList>
                                </gml:LinearRing>
                            </gml:exterior>
                        </gml:PolygonPatch>
                    </gml:patches>
                </gml:Surface>"

As the first and last vertices overlap, why do I get error?

**Comment by rjmartell** [comment]
There appears to be an extraneous point at (557434.869 4889943.527), which is very close to the start/end point (557434.439 4889943.441). If this point is removed, no error is reported.

Perhaps those points are supposed to be coincident?

**Comment by rjmartell** [comment]
What seems to be happening here is that an attempt is made to remove consecutive "duplicate" points that are very nearly coincident (ppm tolerance). In this case, that odd point (557434.869, 4889943.527) is kept and the last one (557434.439, 4889943.441) is ignored so the curve is deemed to be open. This procedure can be modified such that the terminal point is always kept.

**Comment by rjmartell** [comment]
Created new issue: [geomatics-geotk#1](/opengeospatial/geomatics-geotk/issues/1)

**Comment by rjmartell** [comment]
Fixed for next release (1.22).
