### ISSUE TITLE
EPSG schema not created in Derby database

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-gml32#18]
When executing the test suite via the web application and the location specified by the system property `-Dderby.system.home` does not contain a database, one will be automatically created when the test run commences. However, the EPSG schema is not created and populated.

The following exception appears in the stderr log file (tomcat\*stderr\*.log):

    java.sql.SQLException: Table/View 'EPSG_VERSIONHISTORY' does not exist.

**Comment by rjmartell** [comment]
There is a workaround. When the test suite is built (`mvn package`), a copy of the database is created and populated in the user home directory: 

* Unix/Linux: $HOME/.geotoolkit.org/EPSG/7.09
* Windows:  %APPDATA%\Geotoolkit.org\EPSG\7.09

Simple copy the EPSG directory to `derby.system.home`.

**Comment by bermud** [comment]
@rjmartell, since this database is used by several tests, can we just make it available as part of the core TE, and document how to use it? We will have similar issues with WFS 2.0 test and possible other tests.

**Comment by rjmartell** [comment]
The `org.geotoolkit.referencing.factory.epsg.EpsgInstaller` class executes the SQL scripts embedded in the geotk-epsg module. The installer is not called in a web app context, but this can be done in a setup method.

**Comment by rjmartell** [comment]
Adding it to the `teamengine-web` module is a possibility, but this introduces spurious dependencies that have nothing to so with module functionality. Probably better to have each test suite that uses the database first check that it is ready, and create/populate it if not. 

This setup can be done by the `TestRunListener` which already creates a DataSource at the beginning of the test run. It can be easily enhanced to create and populate the database if necessary.
