### ISSUE TITLE
Test method validSurfaceBoundary: Exterior boundary is not simple

### ISSUE THREAD

**Issue by sMorrone** [opengeospatial/ets-gml32#20]
I receive following failure message  
“Test method validSurfaceBoundary: Exterior boundary of surface with @gml:id='_77073d46-7578-4d9b-b031-ab587b75d30a' is not simple”
Below you can find a snippet of my GML file showing the failing geometry. As far as I can see, boundary is simple: it does not self-intersect and the start/end points overlap. 
Would you help?

`<lcv:geometry>
                <gml:Surface gml:id="_77073d46-7578-4d9b-b031-ab587b75d30a" srsName="http://www.opengis.net/def/crs/EPSG/0/EPSG:3044">
                    <gml:patches>
                        <gml:PolygonPatch>
                            <gml:exterior>
                                <gml:LinearRing>
                                    <gml:posList>526923.0335361051 4913412.229461599
                                        526923.9417987193 4913414.642637175 526923.768382421
                                        4913413.515429392 526923.0335361051
                                        4913412.229461599</gml:posList>
                                </gml:LinearRing>
                            </gml:exterior>
                        </gml:PolygonPatch>
                    </gml:patches>
                </gml:Surface>
            </lcv:geometry>
`

**Comment by rjmartell** [comment]
The axis order for EPSG 3044 (ETRS89 / UTM zone 32N) is N,E (see the [EPSG registry](http://epsg-registry.org/)). The coordinate tuples are in E,N order so they're incorrect. I'll check to see why the error message is somewhat misleading.

**Comment by rjmartell** [comment]
Added assertion to check that surface lies within valid area of CRS. This geometry now fails with the following error message:

    SurfaceType[@gml:id='_77073d46-7578-4d9b-b031-ab587b75d30a'] is not covered by valid area of CRS: 
    BOX2D(4061593.237159143 231991.50065096596, 7768690.108665481 768008.4993490342)

**Comment by sMorrone** [comment]
I apologise for not describing the issue properly. 
The failing polygon is part of a GML file containing 1265 polygons (all with same CRS and axis order) but I get  failure only on this one. 
If I delete this failing polygon from the GML file, it validates successfully! 
So I guess the issue does not lie in the erroneous axis order.
Would you please reconsider the issue?
Thanks in advance 
Stefania

**Comment by sMorrone** [comment]
I created a new GML file containing only the abovereferred failing polygon. I changed the coordinate order to Lat Lon.
Here’s the snippet   
`<lcv:geometry> <gml:Surface gml:id="_77073d46-7578-4d9b-b031-ab587b75d30a" srsName="http://www.opengis.net/def/crs/EPSG/0/EPSG:3044"><gml:patches> <gml:PolygonPatch><gml:exterior> <gml:LinearRing> <gml:posList>4913412.229461599 526923.0335361051 4913414.642637175 526923.9417987193 4913413.515429392 526923.768382421 4913412.229461599 526923.0335361051</gml:posList> </gml:LinearRing> </gml:exterior> </gml:PolygonPatch> </gml:patches> </gml:Surface> </lcv:geometry>`

And here follow the 2 failure messages I get
**Test method validSurfaceBoundary:** 
              Exterior boundary of surface with @gml:id='_77073d46-7578-4d9b-b031-ab587b75d30a' is not simple. expected [true] but found [false]         

**Message d1e181_2: 
Test method validSurfaceOrientation:**
              Ring has fewer than 3 points, so orientation cannot be determined

It's maybe worth saying that using GIS environment the polygon displays fine and also topological validation is OK.

**Comment by rjmartell** [comment]
Are those coordinates correct? The area of the surface is only 0.3 m2 which seems awfully small (less than half the area of my desk!).

Because the points are so close together one or more of them are being pruned as likely duplicates, thus the "ring has fewer than three points".

**Comment by sMorrone** [comment]
The GML is an Italian Corine Land Cover file. I guess the area is so small because of a "cut" operation in GIS environment aiming at taking into consideration the regional boundaries (actually Land Cover areas should not be so small ! ).  Would it be possible to modify the error message adding a warning about the fact that when points are too near they're considered as duplicates? maybe it would be good thing to specify which is the buffer ( I mean which is the minimum distance for two points not to be considered as duplicates)

**Comment by sMorrone** [comment]
Don't know if this helps, but I am now validating another INSPIRE GML file consisting of 583 polygons. Only one polygon fails with error message ```
Test method validSurfaceBoundary: Exterior boundary of surface with @gml:id='LOCAL_ID_394' is not simple. ``` This time the area of the polygon is huge : 1177.184 km2 and the **gml:posList** contains 25483 points (first point has same coordinates as the last point). Again, using QGIS, I see that the boundary is closed and does not self-intersect (topological validation is OK)...

**Comment by rjmartell** [comment]
Sliver polygons are typically accidentally created though overlay or cut operations. For this sliver, A = 0.3 m2 and P = 5.2 m, yielding a "thinness" ratio of 0.14 (T = 4 * pi * A/P^2 = 1 for a circle) which suggests this is probably a topology anomaly. Something like this could be flagged in the validation report.

Is it possible to provide a copy of that failing polygon (LOCAL_ID_394)? You can attach it as a ZIP file if you like.

**Comment by sMorrone** [comment]
Here it is. Thanks for your support
[LOCAL_ID_394.txt](https://github.com/opengeospatial/ets-gml32/files/137707/LOCAL_ID_394.txt)

**Comment by rususorinvick** [comment]
Did you manage to get any reply to this issue? I am facing a similar with my Bio-geographical regions polygons: some validate, however other don't. 
You can see that the Continental poly (very large highly detailed poly) is validated: [http://inspire.biodiversity.ro/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&typename=br:Bio-geographicalRegion&featureid=continental](url)
However the Alpine and Marine Black Sea polygons won't validate, having the same error. 
[http://inspire.biodiversity.ro/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&typename=br:Bio-geographicalRegion&featureid=alpine](url)
I have checked GIS topology, using arcgis desktop, I removed any trace of slither polygons, I am encoding the geometry CCW and this is the only error that I get. 

> Exterior boundary of surface with @gml:id='GEOM.RO.ENV.BR.ALP.2016-07-14.2' is not simple. expected [true] but found [false]

**Comment by rjmartell** [comment]
These services are unavailable at the moment (404). Can you attach a sample GML geometry representation that doesn't validate?

**Comment by rjmartell** [comment]
The result appears to be affected by the tolerance for detecting consecutive duplicate positions. The default is 1 ppm. The large Polygon with gml:id="LOCAL_ID_394" validates if this is reduced to 0.5.

**Comment by iuriemaxim** [comment]
This bug was not actually solved. The reduction of the tolerance to 0.5 is just allowing some fake spikes/punctures to pass the test, but some other are still not passing the test. It seems that all roads represented as polygons are not passing the test as the width of the road is significantly smaller than the distance between the vertices. The bug was reopened by Stefania Morrone here https://github.com/opengeospatial/ets-gml32/issues/26
The links provided by https://github.com/rususorinvick are working now.

Iurie
