### ISSUE TITLE
WaterML 2.0 File - CRS issue

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#21]
When testing the enclosed WaterML file it reports The following issue related to CRS

<img width="810" alt="waterml-issues" src="https://cloud.githubusercontent.com/assets/3738898/13529604/260c46fa-e1eb-11e5-9737-9800a8517abd.png">

But a SRS is given:

```
<gml:Point gml:id="location_deddington">
<gml:pos srsName="urn:ogc:def:crs:EPSG::4326">-41.814935 147.568517</gml:pos>
</gml:Point>
```
Is it an issue of the test or the file?

[waterml.xml.zip](https://github.com/opengeospatial/ets-gml32/files/158796/waterml.xml.zip)

**Comment by peterataylor** [comment]
Ah - srsName should be on the gml:Point element, not the gml:pos? 

I.e.
```
<gml:Point gml:id="location_deddington">
   <gml:pos srsName="urn:ogc:def:crs:EPSG::4326">-41.814935 147.568517 </gml:pos>
</gml:Point>
```

Should be

```
<gml:Point gml:id="location_deddington" srsName="urn:ogc:def:crs:EPSG::4326">
   <gml:pos>-41.814935 147.568517 </gml:pos>
</gml:Point>
```

**Comment by bermud** [comment]
@rjmartell, can you please confirm Peter's suggestion?

**Comment by rjmartell** [comment]
The gml:DirectPositionType definition does allow `@srsName`, so it is technically valid. But by far the most common practice is to place the CRS reference on a geometry element.

However, I'll revise the test to also look for a reference in non-deprecated child elements as a fallback (gml:pos, gml:posList).
