### ISSUE TITLE
 Add conformance class configuration into the gml32 test

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-gml32#27]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:
https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by dstenger** [comment]
The test suite covers around half of the conformance classes related to GML application schemas (chapter 2.2 of specification) and conformance classes related to GML documents (chapter 2.4 of the specification).

This is also documented on http://cite.opengeospatial.org/teamengine/about/gml32/3.2.1/site/.

There are no hints regarding a basic conformance class.

Are all CCS part of the basic CC? Is it just the conformance classes related to GML application schemas? Or even just a selection of conformance classes related to GML application schemas?

@bermud What do you think about this?

**Comment by bermud** [comment]
I think is should be:

For application schemas:
- All GML application schemas and 
- GML application schemas defining features and feature collections 

For individuals:
- All GML application schemas and 
- GML Documents

We prototyped separating the tests. Maybe its something we can materialized in the future.

**Comment by dstenger** [comment]
When a test run is started, the user cannot distinct between an application schema and an individual GML document.
For example, if a document [1] is validated, all CCs are executed (no CC is completely skipped).
If a application schema [2] is validated, all CCs are executed but all tests in ```GML Documents``` are skipped.

Thus, there must be a solution which considers validation of both data types.
My proposal: Following CCs are configured as basic conformance classes:
* All GML application schemas
* GML application schemas defining features and feature collections
* GML Documents

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos
[2] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/gml321?SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType&OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&TYPENAME=app:Autos&NAMESPACES=xmlns(app,http://www.deegree.org/app)

**Comment by lgoltz** [comment]
Configured conformance classes listed above as well as the required conformance class  'Preconditions'  as basic (PR #29). 

Tested locally within a docker environment and the URLs above (TEAM Engine 5.2, ETS GML 3.2 current snapshot). The faiure described in https://github.com/opengeospatial/teamengine/issues/284#issuecomment-367694919 occurs.

**Comment by lgoltz** [comment]
> Tested locally within a docker environment and the URLs above (TEAM Engine 5.2, ETS GML 3.2 current snapshot). The faiure described in opengeospatial/teamengine#284 (comment) occurs.

Problem fixed by correcting the position of the element BasicConformanceClasses (commit https://github.com/opengeospatial/ets-gml32/pull/29/commits/87018e02f4ce9451760efd376b7a1c2db587b015).

**Comment by dstenger** [comment]
Configuration was adjusted as there are no Preconditions and name of CC was adjusted.
Commit: https://github.com/opengeospatial/ets-gml32/commit/3c5ab99b1f209932aa6e11207e19531dd95c7875
