### ISSUE TITLE
feature collection of "gml:AbstractFeature"s does not validate

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-gml32#28]
I tried creating a very generic feature collection that could be used to contain all kinds of features. But my GML application schema did not pass the test.

In the process of trying to find out what was wrong, I took the first example in the GML 3.2.1 standard, and tried to test that. That fails too, with the same error, so my conclusion is that the test must be wrong.

Test suite executed: gml32-1.25

GML application schema used: 
[collection-standard-example1.txt](https://github.com/opengeospatial/ets-gml32/files/1480284/collection-standard-example1.txt) (I could not upload a file with extension .xsd, therefore changed to .txt) and also online on https://www.dropbox.com/s/2kkpc44ejaapo6q/collection-standard-example1.xsd?dl=1

The failing test: verify Feature Member Properties 

Reason for test failure:

> The property value "http://www.opengis.net/gml/3.2":AbstractFeature cannot substitute for "http://www.opengis.net/gml/3.2":AbstractFeature in {http://www.example.org/collection-standard-example1}MyFeaturesMemberType. 

I assume that the fails because line 24 says `<element ref="gml:AbstractFeature" />` instead of something like `<element ref="ex:RoadSegments" />`, see e.g. the other example in the standard, also online on https://www.w3.org/TR/sdw-bp/https://www.dropbox.com/s/2hu3sr9tdwnpig1/collection-standard-example2.xsd?dl=1, that does pass test suite gml32-1.25.

**Comment by lgoltz** [comment]
Thank you for reporting. We will do further investigations.

**Comment by keshav-nangare** [comment]
@heidivanparys 

I think substitutionGroup should be`"gml:AbstractGML"`  then it will work.

Can you please test this xsd that I have attached here?: 
[collection-standard-example1_xsd.txt](https://github.com/opengeospatial/ets-gml32/files/2284043/collection-standard-example1_xsd.txt)

**Comment by heidivanparys** [comment]
@keshav-nangare The file you uploaded seems to be the wrong one, it contains a list of links, not a GML application schema.

**Comment by heidivanparys** [comment]
> I think substitutionGroup should be"gml:AbstractGML" then it will work.

The example is taken literally from the GML 3.2.1 standard, and that example uses gml:AbstractFeature, not gml:AbstractGML. So I do not think that replacing gml:AbstractFeature by gml:AbstractGML is the right solution.

I tested again, also on the beta validator (test suite executed: gml32-1.26), there I get the same error.

![billede](https://user-images.githubusercontent.com/11427611/44093204-5f946c6c-9fc2-11e8-8004-ab7c0cd7996e.png)

**Comment by dstenger** [comment]
# Verify fix

Test `verify Feature Member Properties` is not failing anymore when validating collection-standard-example1.txt.
