### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#31]
See opengeospatial/ets-wms13#56 for instructions.

Please use following service implementation: http://cite.deegree.org/deegree-webservices-3.4.0/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos

**Comment by keshav-nangare** [comment]
Updated  with this PR: #33
