### ISSUE TITLE
Introduce Dockerfile and Maven Docker plugin

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#36]
Please see: [How to create Docker Images of test suites](https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites)

**Comment by keshav-nangare** [comment]
@dstenger 

Changes are here: https://github.com/opengeospatial/ets-gml32/tree/feature-issue%2336

**Comment by dstenger** [comment]
@keshav-nangare 
Thank you for your work.
However, there was an update of https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites.
Can you please adjust the Maven configuration according to the updated manual?

**Comment by keshav-nangare** [comment]
@dstenger 

Need correction in the wiki page with docker file path: `/src/main/docker/`.

Can you please update this wiki page?

**Comment by dstenger** [comment]
@keshav-nangare Dockerfile shall be moved to `src/docker/Dockerfile`. Documentation is correct here. Can you please update the pull request?

**Comment by keshav-nangare** [comment]
@dstenger 

Moved Docker file to /src/docker/
