### ISSUE TITLE
Failed to execute the test suite after teamengine upgraded to Jax-rs 2.0 and Jersey 2.28

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-gml32#38]
Reference from: https://github.com/opengeospatial/teamengine/issues/151#issuecomment-465073507

The test suite failed after updating the teamengine with Jax-rs and Jersey to latest version.

**Comment by lgoltz** [comment]
BLOCKED: Requires TEAM Engine 5.5 (https://github.com/opengeospatial/teamengine/issues/151)
