### ISSUE TITLE
Enable Docker support and configure integration tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#40]
Please see:
* https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites
* https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

**Comment by lgoltz** [comment]
@dstenger Is this issue a duplicate of #36 and #31?

**Comment by dstenger** [comment]
Part of this task is covered by those issues. But, the integration test configuration is still missing.

**Comment by dstenger** [comment]
@keshav-nangare 
Build with `mvn clean install site -Pintegration-tests,docker` is failing.
SoapUI specific properties are missing in Maven configuration.
