### ISSUE TITLE
Update tests to use TEAM Engine 5.4

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#43]
Applies to integration and system tests.

SoapUI project must be updated as version was removed from URI to test suites of REST API (also see https://github.com/opengeospatial/teamengine/issues/261).
Please also update Maven configuration and set version of SoapUI Maven Plugin to 5.5.0.

See updated documentation: https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

Example, how this was solved for TEAM Engine tests: https://github.com/opengeospatial/teamengine/issues/400

**Comment by lgoltz** [comment]
Fixed with #41
