### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#48]
Currently, the integration tests are failing on master branch.
Command to reproduce this behavior: `mvn clean install site -Pintegration-tests,docker` (or shorter `mvn clean install -Pintegration-tests`)

Also, a reference implementation can be used to reproduce the behavior manually: http://cite.deegree.org/deegree-webservices-3.4.5/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos

The failures are most likely related to PR https://github.com/opengeospatial/ets-gml32/pull/47.

**Comment by keshav-nangare** [comment]
@dstenger 

I am able to reproduce this issue and found that problem with the same condition.
https://github.com/opengeospatial/ets-gml32/blob/4f81dd502cba1f8d29ca9167a2916b303b1b7eb5/src/main/java/org/opengis/cite/iso19136/general/GeneralSchemaTests.java#L189-L205

Here I got the following schema list:
```
[http://schemas.opengis.net/wfs/2.0/wfs.xsd,
 http://cite.deegree.org/deegree-webservices-3.4.5/services/gml321?SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType&OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&TYPENAME=app:Autos&NAMESPACES=xmlns(app,http%3A%2F%2Fwww.deegree.org%2Fapp),
 http://schemas.opengis.net/gml/3.2.1/gml.xsd]
```
We have already ignored schema from `http://www.opengis.net/gml/3.2`. We can see in above list with one more schema i.e `http://www.opengis.net/wfs/2.0` this should be ignored, then we will get expected result.

I have tried this workaround and it worked fine.

**Comment by keshav-nangare** [comment]
Fixed with #49 PR.

**Comment by dstenger** [comment]
I don't think we should create a workaround for the RI.

What value does this method return on the RI?
```
Attribute targetNS = docElem.getAttributeByName(new QName(
						"targetNamespace"));
```
Obviously, it is ```http://schemas.opengis.net/wfs/2.0/wfs.xsd```, right?
However, this namespace is not declared as target namespace.

Thus, there seems to be a more general bug in this method.

**Comment by dstenger** [comment]
@keshav-nangare Can you please investigate how https://github.com/opengeospatial/ets-gml32/issues/46 alternatively?

**Comment by dstenger** [comment]
@danieluct 
Unfortunately, this issue is blocking the pending release as the pull request for https://github.com/opengeospatial/ets-gml32/issues/46 led to regressions.
We are investigating how to solve the issue but unfortunately we have to postpone the release till this issue is solved.

**Comment by dstenger** [comment]
@danieluct 
Can you provide a test service causing the problem reported in #46?

**Comment by dstenger** [comment]
Decision: We undo PR #47.

**Comment by keshav-nangare** [comment]
@dstenger 

I have reverted #47 PR changes. Please find updated changes in #49 PR.
