### ISSUE TITLE
Provide information about reference implementation and example files

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#6]
- In the description of the test
- Provide a reference  from the main ctl to the test description

**Comment by rjmartell** [comment]
There are several well-known application schemas based on GML 3.2

* [GeoSciML](http://www.geosciml.org/) (v3.2)
* [AIXM](http://www.aixm.aero/) (v5.1)
* [INSPIRE](http://inspire.ec.europa.eu/index.cfm/pageid/2/list/xml-schemas) (v4.0)

**Comment by rjmartell** [comment]
Updated README.

**Comment by bermud** [comment]
Maybe you can also point to this page https://github.com/opengeospatial/cite/wiki/Reference-Implementations, where we have the two initial reference implementations. Great to have other sources as well. Thank you for documenting.
