### ISSUE TITLE
Implement support for GML 3.2.2

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#69]
GML v3.2.2 shall be supported by the test suite.

This issue is a follow up to https://github.com/opengeospatial/ets-gml32/issues/44.

**Comment by ghobona** [comment]
@bpross-52n  @dstenger 

GML 3.2.2 schemas flattened using Oxygen are attached.

[flattened_gml322.zip](https://github.com/opengeospatial/ets-gml32/files/10508837/flattened_gml322.zip)

**Comment by dstenger** [comment]
TODO:

- [ ] Introduce new GML 3.2.2 schemas to test suite.
- [ ] Introduce mechanism to differentiate between GML 3.2.1 and GML 3.2.2 (e.g. radio button in GUI).
- [ ] Compare ATS of both standards (3.2.1 and 3.2.2) and document differences.

**Comment by dstenger** [comment]
Open tasks:
* Update version from `3.2.1` to `3.2`.
* Remove version switch between `3.2.1` and `3.2.2` as `3.2.2` is backwards compatible.
* Update documentation of REST interface: https://github.com/opengeospatial/ets-gml32/tree/master/src/main/javadoc
* Test REST interface with reference implementation: https://cite.deegree.org/deegree-webservices-3.4.30/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos
  * 22 test should pass.
  * 11 tests should be skipped.
