### ISSUE TITLE
Not clear instructions about schema behavior

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#7]
The instructions say the following

_The test run arguments are summarized in Table 3. The Obligation descriptor can have the following values: M (mandatory), O (optional), or C (conditional). A GML application schema may be validated by itself. If the 'xsd' and 'vml' arguments are both present, the 'xsd' value is ignored and the (required) schema reference in the GML instance will be used instead._

Not clear why do we allow to provide both xsd and xml instance at the same time. It seems that if we provide both, the provided xsd file should overwrite the schema reference in the GML.

And how can someone test an instance if it has no xsd reference?

**Comment by rjmartell** [comment]
Is this for an older release? In the current release (r18) the 'gml' argument refers to either a representation of a GML data instance or a GML application schema (this change arose from issue #4). See the latest site docs at http://opengeospatial.github.io/ets-gml32/.

**Comment by rjmartell** [comment]
A GML instance is required to have a schema reference (ISO 19136, A.3.1).
